title: yan's blog
email: wojiabin@live.cn
description: >- # this means to ignore newlines until "baseurl:"
  个人编程随笔及分享
# twitter_username: xxx
github_username: wilkice
minimal_mistakes_skin: air
search: true

remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Shanghai # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# include:
#   - _pages

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "darcy"
  # avatar : "/assets/images/bio-photo.jpg"
  bio    : love code
  links:
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wilkice"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

# footer:
#   links:
#     - label: "Twitter"
#       icon: "fab fa-fw fa-twitter-square"
#       url: "https://twitter.com/"
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/"
#     - label: "Instagram"
#       icon: "fab fa-fw fa-instagram"
#       url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      # author_profile: true
      read_time: true
      comments: true
      # share: true
      related: true
      excerpt_separator: "<!--more-->"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
